services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  respro-web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: respro-web:prototype
    ports:
      - '127.0.0.1:8000:8000'
    volumes:
      - ./data:/data:rw
    environment:
      - RESPRO_WEB_HOST=0.0.0.0
      - RESPRO_WEB_PORT=8000
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  respro-worker:
    image: respro-web:prototype
    command: rq worker --url redis://redis:6379/0 profiling
    volumes:
      - ./data:/data:rw
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
