import { AnalyzeTab } from '../tabs/AnalyzeTab';

export function AnalyzePage({ logic }) {
  return (
    <div className="page-workspace">
      <AnalyzeTab {...pickAnalyzeProps(logic)} />
    </div>
  );
}

function pickAnalyzeProps(logic) {
  return {
    selectedDatabase: logic.selectedDatabase,
    vcfInput: logic.vcfInput,
    setVcfInput: logic.setVcfInput,
    fastaInput: logic.fastaInput,
    setFastaInput: logic.setFastaInput,
    jsonInputId: logic.jsonInputId,
    isRegenerateBusy: logic.isRegenerateBusy,
    runRegenerateFromJson: logic.runRegenerateFromJson,
    uploadFastaFile: logic.uploadFastaFile,
    uploadVcfFile: logic.uploadVcfFile,
    uploadReferenceFile: logic.uploadReferenceFile,
    uploadBamFile: logic.uploadBamFile,
    uploadJsonFile: logic.uploadJsonFile,
    uploadProgress: logic.uploadProgress,
    isUploading: logic.isUploading,
    cancelUpload: logic.cancelUpload,
    activeProfileMode: logic.activeProfileMode,
    setActiveProfileMode: logic.setActiveProfileMode,
    analyzeSubMode: logic.analyzeSubMode,
    setAnalyzeSubMode: logic.setAnalyzeSubMode,
    isProfileBusy: logic.isProfileBusy,
    canCancelJob: logic.canCancelJob,
    isCancelingJob: logic.isCancelingJob,
    cancelActiveJob: logic.cancelActiveJob,
    runSelectedProfile: logic.runSelectedProfile,
    runExampleProfile: logic.runExampleProfile,
    statusError: logic.statusError,
    selectedProfileReportPath: logic.selectedProfileReportPath,
    setSelectedProfileReportPath: logic.setSelectedProfileReportPath,
    reportOptions: logic.reportOptions,
    buildReportUrl: logic.buildReportUrl,
    buildArtifactUrl: logic.buildArtifactUrl,
    batchMode: logic.batchMode,
    setBatchMode: logic.setBatchMode,
    batchVcfFiles: logic.batchVcfFiles,
    batchFastaFiles: logic.batchFastaFiles,
    batchJsonFiles: logic.batchJsonFiles,
    batchReferenceFasta: logic.batchReferenceFasta,
    batchSamples: logic.batchSamples,
    isBatchUploading: logic.isBatchUploading,
    cancelBatchUpload: logic.cancelBatchUpload,
    batchSubmitting: logic.batchSubmitting,
    isBatchDownloadBusy: logic.isBatchDownloadBusy,
    batchError: logic.batchError,
    batchRateLimitCooldown: logic.batchRateLimitCooldown,
    setBatchRateLimitCooldown: logic.setBatchRateLimitCooldown,
    batchSubmitted: logic.batchSubmitted,
    batchMaxSamples: logic.batchMaxSamples,
    sampleLimitPerMinute: logic.sampleLimitPerMinute,
    batchVcfCutoffs: logic.batchVcfCutoffs,
    setBatchVcfCutoffs: logic.setBatchVcfCutoffs,
    addBatchVcfFiles: logic.addBatchVcfFiles,
    addBatchFastaFiles: logic.addBatchFastaFiles,
    addBatchJsonFiles: logic.addBatchJsonFiles,
    addBatchBamFiles: logic.addBatchBamFiles,
    attachBatchBam: logic.attachBatchBam,
    removeBatchFile: logic.removeBatchFile,
    uploadBatchReferenceFasta: logic.uploadBatchReferenceFasta,
    submitBatch: logic.submitBatch,
    downloadAllBatchArtifacts: logic.downloadAllBatchArtifacts,
    resetBatch: logic.resetBatch,
    inlineReportPath: logic.inlineReportPath,
    isAnalyzeScopeLocked: logic.isProfileBusy || logic.isRegenerateBusy || logic.batchSubmitting,
    PROFILE_MODES: logic.PROFILE_MODES,
    resolvedTheme: logic.resolvedTheme,
  };
}
